apiVersion: v1
kind: Secret
metadata:
  name: business-loan-secret
  namespace: business-loan
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: root
  APP_SECURITY_JWT_SECRET: QUJDREVGR0hJSktMTU5PUFFSU1RVVldYWVo0NTY3ODkwQUJDREVGR0hJSktMTU5PUFFSU1RVVg==
