apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-loan-redis
  namespace: business-loan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: business-loan-redis
  template:
    metadata:
      labels:
        app: business-loan-redis
    spec:
      containers:
        - name: redis
          image: redis:7.4-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
          readinessProbe:
            tcpSocket:
              port: 6379
            periodSeconds: 10
            timeoutSeconds: 3
          livenessProbe:
            tcpSocket:
              port: 6379
            periodSeconds: 20
            timeoutSeconds: 3
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: business-loan-redis
  namespace: business-loan
spec:
  selector:
    app: business-loan-redis
  ports:
    - port: 6379
      targetPort: 6379
