spring.application.name=business-loan-management-system
server.port=${SERVER_PORT:8010}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/business_loan_management?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.open-in-view=false
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE:50MB}
spring.servlet.multipart.max-request-size=${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE:50MB}
app.security.jwt.secret=${APP_SECURITY_JWT_SECRET:QUJDREVGR0hJSktMTU5PUFFSU1RVVldYWVo0NTY3ODkwQUJDREVGR0hJSktMTU5PUFFSU1RVVg==}
app.security.jwt.access-token-expiration-ms=${APP_SECURITY_JWT_ACCESS_TOKEN_EXPIRATION_MS:900000}
app.security.jwt.refresh-token-expiration-ms=${APP_SECURITY_JWT_REFRESH_TOKEN_EXPIRATION_MS:604800000}
logging.level.com.employee.loan_system=INFO
